if [ ! -d "generated" ]; then
    mkdir generated
fi
echo Compiling flex and bison...
flex -8 -Cf -ogenerated/lex.yy.c rave.l
bison -dv -ogenerated/y.tab.c rave.y -r state
if [ ! -d "bin" ]; then
    mkdir bin
fi
echo Compiling main.cpp...
g++ -c -O3 -Wall -DLINUX -obin/main.o main.cpp
echo Compiling media.cpp...
g++ -c -O3 -Wall -DLINUX -obin/media.o media.cpp
echo Compiling mesh.cpp...
g++ -c -O3 -Wall -DLINUX -obin/mesh.o mesh.cpp
echo Compiling module.cpp...
g++ -c -O3 -Wall -DLINUX -obin/module.o module.cpp
echo Compiling optimization.cpp...
g++ -c -O3 -Wall -DLINUX -obin/optimization.o optimization.cpp
echo Compiling output.cpp...
g++ -c -O3 -Wall -DLINUX -obin/output.o output.cpp
echo Compiling parse.cpp...
g++ -c -O3 -Wall -DLINUX -obin/parse.o parse.cpp
echo Compiling pipeline.cpp...
g++ -c -O3 -Wall -DLINUX -obin/pipeline.o pipeline.cpp
echo Compiling render.cpp...
g++ -c -O3 -Wall -DLINUX -obin/render.o render.cpp
echo Compiling render3d.cpp...
g++ -c -O3 -Wall -DLINUX -obin/render3d.o render3d.cpp
echo Compiling semantics.cpp...
g++ -c -O3 -Wall -DLINUX -obin/semantics.o semantics.cpp
echo Compiling standardlib.cpp...
g++ -c -O3 -Wall -DLINUX -obin/standardlib.o standardlib.cpp
echo Compiling syntax.cpp...
g++ -c -O3 -Wall -DLINUX -obin/syntax.o syntax.cpp
echo Compiling tostring.cpp...
g++ -c -O3 -Wall -DLINUX -obin/tostring.o tostring.cpp
echo Compiling lex.yy.c...
gcc -c -O3 -Wall -DLINUX -obin/lex.yy.o generated/lex.yy.c
echo Compiling y.tab.c...
gcc -c -O3 -Wall -DLINUX -obin/y.tab.o generated/y.tab.c
echo Linking...
g++ -lncurses -obin/rave -O3 bin/main.o bin/media.o bin/mesh.o bin/module.o bin/optimization.o bin/output.o bin/parse.o bin/pipeline.o bin/render.o bin/render3d.o bin/semantics.o bin/standardlib.o bin/syntax.o bin/tostring.o bin/lex.yy.o bin/y.tab.o
